import { StyleSheet } from "react-native";

import { fiticianTokens } from "../../ui/tokens";

export const publicOnboardingStyles = StyleSheet.create({
  account: {
    alignSelf: "center",
    gap: fiticianTokens.spacing[5],
    maxWidth: 520,
    paddingBottom: fiticianTokens.spacing[6],
    paddingTop: fiticianTokens.spacing[3],
    width: "100%",
  },
  accountHeader: {
    gap: fiticianTokens.spacing[3],
  },
  accountIntro: {
    color: fiticianTokens.colors.muted,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.body,
    lineHeight: 26,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  accountMethod: {
    alignItems: "center",
    backgroundColor: fiticianTokens.colors.surface,
    borderColor: fiticianTokens.colors.line,
    borderRadius: fiticianTokens.radii.medium,
    borderWidth: 1,
    flex: 1,
    minHeight: fiticianTokens.layout.minimumTouchTarget,
    paddingHorizontal: fiticianTokens.spacing[3],
    paddingVertical: fiticianTokens.spacing[3],
  },
  accountMethodSelected: {
    backgroundColor: fiticianTokens.colors.aquaAtmosphere,
    borderColor: fiticianTokens.colors.aqua,
  },
  accountMethodText: {
    color: fiticianTokens.colors.muted,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.sm,
    fontWeight: fiticianTokens.typography.fontWeight.bold,
    textAlign: "center",
    writingDirection: "rtl",
  },
  accountMethodTextSelected: {
    color: fiticianTokens.colors.ink,
  },
  accountMethods: {
    flexDirection: "row",
    gap: fiticianTokens.spacing[2],
  },
  accountModeToggle: {
    alignSelf: "center",
    color: fiticianTokens.colors.aqua,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.sm,
    fontWeight: fiticianTokens.typography.fontWeight.bold,
    minHeight: fiticianTokens.layout.minimumTouchTarget,
    paddingHorizontal: fiticianTokens.spacing[2],
    paddingVertical: fiticianTokens.spacing[2],
    textAlign: "center",
    writingDirection: "rtl",
  },
  accountProvider: {
    flex: 1,
  },
  accountProviders: {
    flexDirection: "row",
    gap: fiticianTokens.spacing[3],
  },
  accountSecurity: {
    alignItems: "center",
    backgroundColor: fiticianTokens.colors.aquaAtmosphere,
    borderColor: fiticianTokens.colors.lineStrong,
    borderRadius: fiticianTokens.radii.large,
    borderWidth: 1,
    flexDirection: "row",
    gap: fiticianTokens.spacing[3],
    padding: fiticianTokens.spacing[4],
  },
  accountSecurityCopy: {
    flex: 1,
    gap: fiticianTokens.spacing[1],
  },
  accountSecurityBody: {
    color: fiticianTokens.colors.muted,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.xs,
    lineHeight: 20,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  accountSecurityTitle: {
    color: fiticianTokens.colors.ink,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.sm,
    fontWeight: fiticianTokens.typography.fontWeight.bold,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  accountTitle: {
    color: fiticianTokens.colors.ink,
    fontFamily: fiticianTokens.typography.fontFamily.displayPersian,
    fontSize: 34,
    lineHeight: 45,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  accountTopline: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: fiticianTokens.spacing[3],
    justifyContent: "space-between",
  },
  appleProvider: {
    alignItems: "center",
    backgroundColor: fiticianTokens.colors.surface,
    borderColor: fiticianTokens.colors.line,
    borderRadius: fiticianTokens.radii.medium,
    borderWidth: 1,
    flex: 1,
    gap: fiticianTokens.spacing[1],
    justifyContent: "center",
    minHeight: 64,
    opacity: 0.48,
    paddingHorizontal: fiticianTokens.spacing[2],
  },
  appleProviderLabel: {
    color: fiticianTokens.colors.muted,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.sm,
    textAlign: "center",
    writingDirection: "ltr",
  },
  appleProviderHint: {
    color: fiticianTokens.colors.muted,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.xs,
    textAlign: "center",
    writingDirection: "rtl",
  },
  phoneActions: {
    alignItems: "center",
    flexDirection: "row",
    gap: fiticianTokens.spacing[2],
    justifyContent: "space-between",
  },
  providerButton: {
    flex: 1,
  },
  backButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    borderColor: fiticianTokens.colors.line,
    borderRadius: fiticianTokens.radii.pill,
    borderWidth: 1,
    height: fiticianTokens.layout.minimumTouchTarget,
    justifyContent: "center",
    width: fiticianTokens.layout.minimumTouchTarget,
  },
  backButtonIcon: {
    color: fiticianTokens.colors.mist,
  },
  bodyConfirmation: {
    alignItems: "center",
    backgroundColor: fiticianTokens.colors.surfaceTranslucent,
    borderColor: fiticianTokens.colors.lineStrong,
    borderRadius: fiticianTokens.radii.medium,
    borderWidth: 1,
    flexDirection: "row",
    gap: fiticianTokens.spacing[3],
    minHeight: fiticianTokens.layout.minimumTouchTarget,
    paddingHorizontal: fiticianTokens.spacing[3],
    paddingVertical: fiticianTokens.spacing[3],
  },
  bodyConfirmationText: {
    color: fiticianTokens.colors.ink,
    flex: 1,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.sm,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  bodyFields: {
    gap: fiticianTokens.spacing[4],
  },
  checkboxCard: {
    alignItems: "center",
    backgroundColor: fiticianTokens.colors.surfaceTranslucent,
    borderColor: fiticianTokens.colors.line,
    borderRadius: fiticianTokens.radii.medium,
    borderWidth: 1,
    flexDirection: "row",
    gap: fiticianTokens.spacing[3],
    minHeight: fiticianTokens.layout.minimumTouchTarget,
    paddingHorizontal: fiticianTokens.spacing[3],
    paddingVertical: fiticianTokens.spacing[3],
  },
  checkboxCardSelected: {
    backgroundColor: fiticianTokens.colors.aquaAtmosphere,
    borderColor: fiticianTokens.colors.aqua,
  },
  checkboxIndicator: {
    alignItems: "center",
    borderColor: fiticianTokens.colors.muted,
    borderRadius: fiticianTokens.radii.small,
    borderWidth: 1,
    height: 22,
    justifyContent: "center",
    width: 22,
  },
  checkboxIndicatorSelected: {
    backgroundColor: fiticianTokens.colors.aqua,
    borderColor: fiticianTokens.colors.aqua,
  },
  checkboxText: {
    color: fiticianTokens.colors.ink,
    flex: 1,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.sm,
    lineHeight: 22,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  choiceCard: {
    alignItems: "center",
    backgroundColor: fiticianTokens.colors.surfaceTranslucent,
    borderColor: fiticianTokens.colors.line,
    borderRadius: fiticianTokens.radii.large,
    borderWidth: 1,
    flexDirection: "row",
    gap: fiticianTokens.spacing[3],
    minHeight: 84,
    paddingHorizontal: fiticianTokens.spacing[4],
    paddingVertical: fiticianTokens.spacing[3],
  },
  choiceCardDisabled: {
    opacity: 0.45,
  },
  choiceCardSelected: {
    backgroundColor: fiticianTokens.colors.aquaAtmosphere,
    borderColor: fiticianTokens.colors.aqua,
    shadowColor: fiticianTokens.colors.aqua,
    shadowOpacity: 0.22,
    shadowRadius: 12,
  },
  choiceContent: {
    flex: 1,
    gap: fiticianTokens.spacing[1],
    minWidth: 0,
  },
  choiceDescription: {
    color: fiticianTokens.colors.muted,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.xs,
    lineHeight: 18,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  choiceGrid: {
    gap: fiticianTokens.spacing[3],
  },
  choiceIcon: {
    alignItems: "center",
    backgroundColor: fiticianTokens.colors.surfaceInteractive,
    borderColor: fiticianTokens.colors.lineStrong,
    borderRadius: fiticianTokens.radii.medium,
    borderWidth: 1,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  choiceIconSelected: {
    backgroundColor: fiticianTokens.colors.aqua,
    borderColor: fiticianTokens.colors.aqua,
  },
  choiceIconText: {
    color: fiticianTokens.colors.aqua,
  },
  choiceIconTextSelected: {
    color: fiticianTokens.colors.canvas,
  },
  choiceLabel: {
    color: fiticianTokens.colors.ink,
    flexShrink: 1,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.body,
    fontWeight: fiticianTokens.typography.fontWeight.bold,
    lineHeight: 24,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  content: {
    gap: fiticianTokens.spacing[4],
    width: "100%",
  },
  divider: {
    alignItems: "center",
    flexDirection: "row",
    gap: fiticianTokens.spacing[3],
  },
  dividerLine: {
    backgroundColor: fiticianTokens.colors.line,
    flex: 1,
    height: 1,
  },
  dividerText: {
    color: fiticianTokens.colors.muted,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.xs,
    textAlign: "center",
    writingDirection: "rtl",
  },
  dateGrid: {
    flexDirection: "row",
    gap: fiticianTokens.spacing[2],
  },
  dateSelector: {
    alignItems: "stretch",
    flex: 1,
    gap: fiticianTokens.spacing[2],
  },
  dateSelectorButton: {
    alignItems: "center",
    backgroundColor: fiticianTokens.colors.surface,
    borderColor: fiticianTokens.colors.line,
    borderRadius: fiticianTokens.radii.medium,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 64,
    paddingHorizontal: fiticianTokens.spacing[2],
  },
  dateSelectorLabel: {
    color: fiticianTokens.colors.muted,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.xs,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  dateSelectorValue: {
    color: fiticianTokens.colors.ink,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.body,
    fontWeight: fiticianTokens.typography.fontWeight.bold,
    textAlign: "center",
    writingDirection: "ltr",
  },
  error: {
    color: fiticianTokens.colors.danger,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.sm,
    lineHeight: 22,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  fieldStack: {
    gap: fiticianTokens.spacing[4],
  },
  modalBackdrop: {
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.72)",
    flex: 1,
    justifyContent: "center",
    padding: fiticianTokens.spacing[4],
  },
  modalCard: {
    backgroundColor: fiticianTokens.colors.surfaceRaised,
    borderColor: fiticianTokens.colors.lineStrong,
    borderRadius: fiticianTokens.radii.large,
    borderWidth: 1,
    maxHeight: "80%",
    width: "100%",
  },
  modalOption: {
    alignItems: "center",
    borderBottomColor: fiticianTokens.colors.line,
    borderBottomWidth: 1,
    minHeight: fiticianTokens.layout.minimumTouchTarget,
    paddingHorizontal: fiticianTokens.spacing[4],
    paddingVertical: fiticianTokens.spacing[3],
  },
  modalOptionSelected: {
    backgroundColor: fiticianTokens.colors.aquaAtmosphere,
  },
  modalOptionText: {
    color: fiticianTokens.colors.ink,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.body,
    textAlign: "center",
    writingDirection: "ltr",
  },
  modalTitle: {
    color: fiticianTokens.colors.ink,
    fontFamily: fiticianTokens.typography.fontFamily.displayPersian,
    fontSize: fiticianTokens.typography.fontSize.h3,
    padding: fiticianTokens.spacing[4],
    textAlign: "auto",
    writingDirection: "rtl",
  },
  progressBar: {
    backgroundColor: fiticianTokens.colors.line,
    borderRadius: fiticianTokens.radii.pill,
    height: 5,
    overflow: "hidden",
  },
  progressFill: {
    backgroundColor: fiticianTokens.colors.aqua,
    borderRadius: fiticianTokens.radii.pill,
    height: "100%",
  },
  progressLabel: {
    color: fiticianTokens.colors.muted,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.sm,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  progressStack: {
    gap: fiticianTokens.spacing[2],
  },
  question: {
    alignSelf: "center",
    gap: fiticianTokens.spacing[5],
    maxWidth: 520,
    minHeight: 560,
    paddingBottom: fiticianTokens.spacing[6],
    paddingTop: fiticianTokens.spacing[2],
    width: "100%",
  },
  questionDescription: {
    color: fiticianTokens.colors.muted,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.sm,
    lineHeight: 24,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  questionForm: {
    gap: fiticianTokens.spacing[5],
  },
  questionTitle: {
    color: fiticianTokens.colors.ink,
    fontFamily: fiticianTokens.typography.fontFamily.displayPersian,
    fontSize: 34,
    lineHeight: 45,
    maxWidth: "94%",
    textAlign: "auto",
    writingDirection: "rtl",
  },
  stageLabel: {
    color: fiticianTokens.colors.muted,
    flexShrink: 1,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.xs,
    fontWeight: fiticianTokens.typography.fontWeight.bold,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  stageLabelActive: {
    color: fiticianTokens.colors.ink,
  },
  stageLabelComplete: {
    color: fiticianTokens.colors.aqua,
  },
  stageMarker: {
    alignItems: "center",
    borderColor: fiticianTokens.colors.line,
    borderRadius: fiticianTokens.radii.pill,
    borderWidth: 1,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  stageMarkerActive: {
    backgroundColor: fiticianTokens.colors.aqua,
    borderColor: fiticianTokens.colors.aqua,
  },
  stageMarkerComplete: {
    backgroundColor: fiticianTokens.colors.aquaAtmosphere,
    borderColor: fiticianTokens.colors.lineStrong,
  },
  stageMarkerText: {
    color: fiticianTokens.colors.muted,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.xs,
    fontWeight: fiticianTokens.typography.fontWeight.extraBold,
    textAlign: "center",
  },
  stageMarkerTextActive: {
    color: fiticianTokens.colors.canvas,
  },
  stageMarkerTextComplete: {
    color: fiticianTokens.colors.aqua,
  },
  stageRow: {
    direction: "rtl",
    flexDirection: "row",
    gap: fiticianTokens.spacing[2],
    width: "100%",
  },
  stageItem: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: fiticianTokens.spacing[2],
    minWidth: 0,
  },
  textButton: {
    alignSelf: "flex-start",
    color: fiticianTokens.colors.aqua,
    fontFamily: fiticianTokens.typography.fontFamily.bodyPersian,
    fontSize: fiticianTokens.typography.fontSize.sm,
    fontWeight: fiticianTokens.typography.fontWeight.bold,
    minHeight: fiticianTokens.layout.minimumTouchTarget,
    paddingHorizontal: fiticianTokens.spacing[2],
    paddingVertical: fiticianTokens.spacing[2],
    textAlign: "auto",
    writingDirection: "rtl",
  },
  footer: {
    gap: fiticianTokens.spacing[3],
  },
});
