from enum import StrEnum


class WorkoutReviewStatus(StrEnum):
    PENDING = "pending"
    CLAIMED = "claimed"
    APPROVED = "approved"
    SUPERSEDED = "superseded"


class WorkoutReviewErrorCode(StrEnum):
    COACH_ROLE_REQUIRED = "COACH_ROLE_REQUIRED"
    REVIEW_NOT_FOUND = "REVIEW_NOT_FOUND"
    REVIEW_ALREADY_CLAIMED = "REVIEW_ALREADY_CLAIMED"
    REVIEW_LEASE_EXPIRED = "REVIEW_LEASE_EXPIRED"
    STALE_DRAFT_REVISION = "STALE_DRAFT_REVISION"
    INVALID_DRAFT = "INVALID_DRAFT"
    EXERCISE_NOT_ALLOWED = "EXERCISE_NOT_ALLOWED"
    REVIEW_ALREADY_APPROVED = "REVIEW_ALREADY_APPROVED"
    REVIEW_SUPERSEDED = "REVIEW_SUPERSEDED"
