import { expect, it } from "vitest";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

it("keeps onboarding guided, native, and RTL-friendly", async () => {
  const entrySource = await readFile(resolve(import.meta.dirname, "../app/(public)/index.tsx"), "utf8");
  const source = await readFile(resolve(import.meta.dirname, "OnboardingScreen.tsx"), "utf8");
  const publicSource = await readFile(resolve(import.meta.dirname, "PublicOnboardingScreen.tsx"), "utf8");
  const publicQuestionSource = await readFile(resolve(import.meta.dirname, "public/GuidedSharedProfileQuestions.tsx"), "utf8");
  const publicTrainingSource = await readFile(resolve(import.meta.dirname, "public/GuidedTrainingQuestions.tsx"), "utf8");
  const publicNutritionSource = await readFile(resolve(import.meta.dirname, "public/PublicNutritionOnboardingFlow.tsx"), "utf8");
  const publicAccountSource = await readFile(resolve(import.meta.dirname, "public/PublicAccountStep.tsx"), "utf8");

  expect(entrySource).toMatch(/public-entry-hero\.jpg/);
  expect(entrySource).toMatch(/Media/);
  expect(entrySource).toMatch(/const landing = authCopy\.landing/);
  expect(entrySource).toMatch(/landing\.hero\.title/);
  expect(entrySource).toMatch(/landing\.process\.title/);
  expect(entrySource).toMatch(/landing\.intelligence\.title/);
  expect(entrySource).not.toMatch(/pillRow/);
  expect(source).toMatch(/getOnboardingSteps/);
  expect(source).toMatch(/ProgressBar/);
  expect(source).toMatch(/questionIndex/);
  expect(source).toMatch(/modeIcon/);
  expect(source).toMatch(/variant="glass"/);
  expect(source).toMatch(/writingDirection: "rtl"/);
  expect(source).toMatch(/بیشتر در چه زمینه‌ای به کمک نیاز داری؟/);
  expect(source).toMatch(/برنامه شخصی براساس بدن، هدف، سطح، زمان و تجهیزات/);
  expect(source).toMatch(/getOnboardingStageProgress/);
  expect(source).toMatch(/logout/);
  expect(publicSource).toMatch(/SecurePublicOnboardingDraftStore/);
  expect(publicSource).toMatch(/PUBLIC_ONBOARDING_SOURCE/);
  expect(publicSource).toMatch(/StateSkeleton/);
  expect(publicSource).toMatch(/GuidedSharedProfileQuestions/);
  expect(publicSource).toMatch(/GuidedTrainingQuestions/);
  expect(publicSource).toMatch(/PublicNutritionOnboardingFlow/);
  expect(publicSource).toMatch(/PublicAccountStep/);
  const headerNote = publicSource.slice(publicSource.indexOf("headerNote:"), publicSource.indexOf("loadingScreen:"));
  expect(headerNote).toContain('textAlign: "auto"');
  expect(headerNote).toContain('writingDirection: "rtl"');
  expect(publicSource).not.toMatch(/SharedProfileStage/);
  expect(publicSource).not.toMatch(/TrainingProfileStage/);
  expect(publicSource).not.toMatch(/SafetyStage/);
  expect(publicSource).not.toMatch(/ExerciseStage/);
  expect(publicSource).not.toMatch(/NutritionBasicsStage/);
  expect(publicSource).not.toMatch(/NutritionPreferencesStage/);
  expect(publicSource).not.toMatch(/getOnboardingStageProgress/);
  expect(publicSource).not.toMatch(/WebView/);
  expect(publicQuestionSource).toMatch(/دوست داری چه صدایت کنیم؟/);
  expect(publicQuestionSource).toMatch(/چه تاریخی به دنیا آمدی؟/);
  expect(publicQuestionSource).toMatch(/جنسیتت چیست؟/);
  expect(publicQuestionSource).toMatch(/قد و وزنت چقدر است؟/);
  expect(publicQuestionSource).toMatch(/هدف اصلی تو چیست؟/);
  expect(publicQuestionSource).toMatch(/female/);
  expect(publicQuestionSource).toMatch(/male/);
  expect(publicQuestionSource).not.toMatch(/prefer_not_to_say/);
  expect(publicQuestionSource).not.toMatch(/سایر/);
  expect(publicTrainingSource).toMatch(/first_month/);
  expect(publicTrainingSource).toMatch(/training_location/);
  expect(publicTrainingSource).toMatch(/bodyweight_only/);
  expect(publicTrainingSource).toMatch(/userSelectablePriorityMuscles/);
  expect(publicTrainingSource).toMatch(/training_cautions/);
  expect(publicNutritionSource).toMatch(/در حال حاضر تمرین منظم داری؟/);
  expect(publicNutritionSource).toMatch(/میزان فعالیت روزانه‌ات چقدر است؟/);
  expect(publicNutritionSource).toMatch(/بودجه ماهانه غذای تو چقدر است؟/);
  expect(publicNutritionSource).toMatch(/چه سبک غذایی را ترجیح می‌دهی؟/);
  expect(publicAccountSource).toMatch(/حالا حسابت را بساز/);
  expect(publicAccountSource).toMatch(/register/);
  expect(publicAccountSource).toMatch(/signInWithPassword/);
  expect(publicAccountSource).toMatch(/sendPhoneOtp/);
  expect(publicAccountSource).toMatch(/verifyPhoneOtp/);
  expect(publicAccountSource).toMatch(/signInWithGoogle/);
  expect(source).toMatch(/<Screen/);
  expect(source).toContain('textAlign: "auto"');
  expect(source).toContain('writingDirection: "rtl"');
});
