from dataclasses import dataclass

from app.exercises.enums import MovementPattern, MuscleGroup
from app.profile.enums import ExperienceLevel, FitnessGoal
from app.training_templates.models import TrainingTemplateMethod


@dataclass(frozen=True)
class TemplateSlotSeed:
    exercise_slug_hint: str
    target_muscles: tuple[MuscleGroup, ...]
    movement_pattern: MovementPattern
    placeholder_name_en: str | None = None
    placeholder_name_fa: str | None = None
    sets: int = 3
    rep_min: int = 8
    rep_max: int = 12
    target_rir: int = 2
    rest_seconds: int = 90
    intensity_method: TrainingTemplateMethod = TrainingTemplateMethod.STANDARD


@dataclass(frozen=True)
class TemplateDaySeed:
    title_en: str
    title_fa: str
    direct_target_muscles: tuple[MuscleGroup, ...]
    slots: tuple[TemplateSlotSeed, ...]


@dataclass(frozen=True)
class TrainingProgramTemplateSeed:
    slug: str
    name_en: str
    name_fa: str
    description_en: str
    description_fa: str
    days_per_week: int
    training_level: ExperienceLevel
    focus_tags: tuple[str, ...]
    intensity_methods: tuple[TrainingTemplateMethod, ...]
    days: tuple[TemplateDaySeed, ...]
    fitness_goal: FitnessGoal = FitnessGoal.BUILD_MUSCLE


M = MuscleGroup
P = MovementPattern
Method = TrainingTemplateMethod
Level = ExperienceLevel

SOURCE_NAME = "Fitsho original evidence-informed template"
SOURCE_URL = "https://pubmed.ncbi.nlm.nih.gov/38595233/"


def _slot(
    slug: str,
    muscles: tuple[MuscleGroup, ...],
    pattern: MovementPattern,
    *,
    placeholder_en: str | None = None,
    placeholder_fa: str | None = None,
    sets: int = 3,
    reps: tuple[int, int] = (8, 12),
    rir: int = 2,
    rest: int = 90,
    method: TrainingTemplateMethod = Method.STANDARD,
) -> TemplateSlotSeed:
    return TemplateSlotSeed(
        exercise_slug_hint=slug,
        target_muscles=muscles,
        movement_pattern=pattern,
        placeholder_name_en=placeholder_en,
        placeholder_name_fa=placeholder_fa,
        sets=sets,
        rep_min=reps[0],
        rep_max=reps[1],
        target_rir=rir,
        rest_seconds=rest,
        intensity_method=method,
    )


CHEST = _slot("dumbbell-bench-press", (M.CHEST,), P.HORIZONTAL_PUSH, sets=4)
INCLINE_CHEST = _slot(
    "incline-dumbbell-bench-press",
    (M.CHEST,),
    P.HORIZONTAL_PUSH,
    placeholder_en="Incline Dumbbell Bench Press",
    placeholder_fa="پرس سینه بالا سینه دمبل",
)
CABLE_FLY = _slot(
    "cable-fly",
    (M.CHEST,),
    P.HORIZONTAL_PUSH,
    placeholder_en="Cable Fly",
    placeholder_fa="فلای کابل",
    reps=(12, 15),
    rest=60,
)
BACK_ROW = _slot("barbell-bent-over-row", (M.BACK,), P.HORIZONTAL_PULL, sets=4)
LAT_PULLDOWN = _slot(
    "lat-pulldown",
    (M.BACK,),
    P.VERTICAL_PULL,
    placeholder_en="Lat Pulldown",
    placeholder_fa="لت پول‌داون",
)
CABLE_PULLDOWN = _slot(
    "cable-pullover",
    (M.BACK,),
    P.VERTICAL_PULL,
    placeholder_en="Cable Pullover",
    placeholder_fa="پلاور کابل",
    reps=(12, 15),
    rest=60,
)
SHOULDER_PRESS = _slot("smith-machine-shoulder-press", (M.SHOULDERS,), P.VERTICAL_PUSH)
LATERAL_RAISE = _slot(
    "dumbbell-lateral-raise", (M.SHOULDERS,), P.SHOULDER_ABDUCTION, reps=(12, 20), rest=60
)
REAR_DELT = _slot("rear-delt-fly", (M.SHOULDERS,), P.HORIZONTAL_PULL, reps=(12, 20), rest=60)
SHRUG = _slot(
    "dumbbell-shrug",
    (M.TRAPS,),
    P.SHRUG,
    placeholder_en="Dumbbell Shrug",
    placeholder_fa="شراگ دمبل",
    reps=(10, 15),
)
BICEPS = _slot("dumbbell-curl", (M.BICEPS,), P.ELBOW_FLEXION, reps=(10, 15), rest=60)
HAMMER_CURL = _slot("hammer-curl", (M.BICEPS,), P.ELBOW_FLEXION, reps=(10, 15), rest=60)
TRICEPS = _slot(
    "overhead-dumbbell-extension", (M.TRICEPS,), P.ELBOW_EXTENSION, reps=(10, 15), rest=60
)
PUSH_DOWN = _slot(
    "cable-triceps-pushdown",
    (M.TRICEPS,),
    P.ELBOW_EXTENSION,
    placeholder_en="Cable Triceps Pushdown",
    placeholder_fa="پشت بازو سیم‌کش",
    reps=(10, 15),
    rest=60,
)
SQUAT = _slot("goblet-squat", (M.QUADRICEPS,), P.SQUAT, sets=4)
LEG_PRESS = _slot("leg-press", (M.QUADRICEPS,), P.SQUAT, sets=4)
LEG_EXTENSION = _slot("leg-extension", (M.QUADRICEPS,), P.KNEE_EXTENSION, reps=(12, 15), rest=60)
LUNGE = _slot("dumbbell-lunge", (M.QUADRICEPS, M.GLUTES), P.LUNGE)
RDL = _slot("romanian-deadlift", (M.HAMSTRINGS, M.GLUTES), P.HIP_HINGE, sets=4)
LEG_CURL = _slot(
    "seated-leg-curl",
    (M.HAMSTRINGS,),
    P.KNEE_FLEXION,
    placeholder_en="Seated Leg Curl",
    placeholder_fa="پشت پا دستگاه نشسته",
    reps=(10, 15),
)
GLUTE_BRIDGE = _slot("glute-bridge", (M.GLUTES,), P.HIP_EXTENSION)
CALF = _slot("standing-calf-raise", (M.CALVES,), P.CALF_RAISE, reps=(10, 20), rest=60)
CORE = _slot(
    "dead-bug",
    (M.ABS,),
    P.CORE_ANTI_EXTENSION,
    placeholder_en="Dead Bug",
    placeholder_fa="ددباگ",
    reps=(8, 12),
    rest=45,
)


def _day(
    title_en: str,
    title_fa: str,
    muscles: tuple[MuscleGroup, ...],
    *slots: TemplateSlotSeed,
) -> TemplateDaySeed:
    return TemplateDaySeed(title_en, title_fa, muscles, slots)


def _template(
    slug: str,
    name_en: str,
    name_fa: str,
    description_en: str,
    description_fa: str,
    days_per_week: int,
    level: ExperienceLevel,
    tags: tuple[str, ...],
    methods: tuple[TrainingTemplateMethod, ...],
    *days: TemplateDaySeed,
) -> TrainingProgramTemplateSeed:
    return TrainingProgramTemplateSeed(
        slug=slug,
        name_en=name_en,
        name_fa=name_fa,
        description_en=description_en,
        description_fa=description_fa,
        days_per_week=days_per_week,
        training_level=level,
        focus_tags=tags,
        intensity_methods=methods,
        days=days,
    )


TRAINING_PROGRAM_TEMPLATE_SEEDS: tuple[TrainingProgramTemplateSeed, ...] = (
    _template(
        "two-day-full-body-foundation",
        "Two-Day Full Body Foundation",
        "پایه تمام‌بدن دو روزه",
        "Alternating full-body sessions for a beginner building consistent movement practice.",
        "جلسات تمام‌بدن چرخشی برای مبتدی که روی تکرار باکیفیت حرکات پایه تمرکز دارد.",
        2,
        Level.BEGINNER,
        ("classic", "full_body", "foundation"),
        (Method.STANDARD,),
        _day(
            "Full Body A",
            "تمام‌بدن A",
            (M.CHEST, M.BACK, M.QUADRICEPS),
            CHEST,
            BACK_ROW,
            SQUAT,
            CORE,
        ),
        _day(
            "Full Body B",
            "تمام‌بدن B",
            (M.SHOULDERS, M.HAMSTRINGS, M.GLUTES),
            SHOULDER_PRESS,
            LAT_PULLDOWN,
            RDL,
            GLUTE_BRIDGE,
            CALF,
        ),
    ),
    _template(
        "two-day-upper-lower-foundation",
        "Two-Day Upper / Lower Foundation",
        "پایه بالاتنه / پایین‌تنه دو روزه",
        "A simple upper/lower split with enough recovery between two weekly sessions.",
        "تقسیم ساده بالاتنه و پایین‌تنه با ریکاوری کافی بین دو جلسهٔ هفتگی.",
        2,
        Level.BEGINNER,
        ("upper_lower", "classic", "foundation"),
        (Method.STANDARD,),
        _day(
            "Upper Body",
            "بالاتنه",
            (M.CHEST, M.BACK, M.SHOULDERS),
            CHEST,
            BACK_ROW,
            SHOULDER_PRESS,
            BICEPS,
            TRICEPS,
        ),
        _day(
            "Lower Body",
            "پایین‌تنه",
            (M.QUADRICEPS, M.HAMSTRINGS, M.GLUTES, M.CALVES),
            SQUAT,
            RDL,
            GLUTE_BRIDGE,
            CALF,
        ),
    ),
    _template(
        "two-day-full-body-hypertrophy",
        "Two-Day Full Body Hypertrophy",
        "هایپرتروفی تمام‌بدن دو روزه",
        "A higher-volume full-body A/B structure for an intermediate lifter "
        "with two training days.",
        "ساختار A/B تمام‌بدن با حجم بیشتر برای ورزشکار متوسط با دو روز تمرین.",
        2,
        Level.INTERMEDIATE,
        ("full_body", "hypertrophy", "balanced"),
        (Method.STANDARD,),
        _day(
            "Full Body Push Bias",
            "تمام‌بدن با تأکید پوش",
            (M.CHEST, M.QUADRICEPS, M.TRICEPS),
            CHEST,
            INCLINE_CHEST,
            LEG_PRESS,
            LEG_EXTENSION,
            TRICEPS,
        ),
        _day(
            "Full Body Pull Bias",
            "تمام‌بدن با تأکید پول",
            (M.BACK, M.HAMSTRINGS, M.BICEPS),
            BACK_ROW,
            LAT_PULLDOWN,
            RDL,
            LEG_CURL,
            BICEPS,
        ),
    ),
    _template(
        "two-day-upper-lower-strength-hypertrophy",
        "Two-Day Upper / Lower Strength-Hypertrophy",
        "قدرت / هایپرتروفی بالاتنه پایین‌تنه دو روزه",
        "Compound-first upper/lower sessions with moderate accessory volume.",
        "جلسات بالاتنه و پایین‌تنه با اولویت حرکات چندمفصلی و حجم کمکی متوسط.",
        2,
        Level.INTERMEDIATE,
        ("upper_lower", "strength_hypertrophy", "compound_first"),
        (Method.STANDARD,),
        _day(
            "Upper Strength",
            "قدرت بالاتنه",
            (M.CHEST, M.BACK, M.SHOULDERS),
            CHEST,
            BACK_ROW,
            SHOULDER_PRESS,
            BICEPS,
        ),
        _day(
            "Lower Strength",
            "قدرت پایین‌تنه",
            (M.QUADRICEPS, M.HAMSTRINGS, M.GLUTES),
            LEG_PRESS,
            RDL,
            LUNGE,
            CALF,
        ),
    ),
    _template(
        "two-day-full-body-superset",
        "Two-Day Full Body Supersets",
        "تمام‌بدن سوپرست دو روزه",
        "Time-efficient antagonist pairings for an experienced trainee with limited weekly access.",
        "جفت‌کردن عضلات مخالف برای ورزشکار باتجربه با زمان محدود در هفته.",
        2,
        Level.ADVANCED,
        ("full_body", "time_efficient", "superset"),
        (Method.STANDARD, Method.SUPERSET),
        _day(
            "Full Body A",
            "تمام‌بدن A",
            (M.CHEST, M.BACK, M.QUADRICEPS),
            CHEST,
            BACK_ROW,
            SQUAT,
            _slot("dumbbell-curl", (M.BICEPS,), P.ELBOW_FLEXION, method=Method.SUPERSET),
            _slot(
                "overhead-dumbbell-extension",
                (M.TRICEPS,),
                P.ELBOW_EXTENSION,
                method=Method.SUPERSET,
            ),
        ),
        _day(
            "Full Body B",
            "تمام‌بدن B",
            (M.SHOULDERS, M.HAMSTRINGS, M.GLUTES),
            SHOULDER_PRESS,
            RDL,
            GLUTE_BRIDGE,
            _slot(
                "dumbbell-lateral-raise",
                (M.SHOULDERS,),
                P.SHOULDER_ABDUCTION,
                method=Method.SUPERSET,
            ),
            _slot("standing-calf-raise", (M.CALVES,), P.CALF_RAISE, method=Method.SUPERSET),
        ),
    ),
    _template(
        "three-day-full-body-foundation",
        "Three-Day Full Body Foundation",
        "پایه تمام‌بدن سه روزه",
        "Three low-complexity full-body exposures for a new lifter.",
        "سه مواجههٔ تمام‌بدن کم‌پیچیدگی برای ورزشکار تازه‌کار.",
        3,
        Level.BEGINNER,
        ("full_body", "foundation", "three_day"),
        (Method.STANDARD,),
        _day(
            "Full Body A",
            "تمام‌بدن A",
            (M.CHEST, M.BACK, M.QUADRICEPS),
            CHEST,
            BACK_ROW,
            SQUAT,
            CORE,
        ),
        _day(
            "Full Body B",
            "تمام‌بدن B",
            (M.SHOULDERS, M.HAMSTRINGS, M.GLUTES),
            SHOULDER_PRESS,
            LAT_PULLDOWN,
            RDL,
            CALF,
        ),
        _day(
            "Full Body C",
            "تمام‌بدن C",
            (M.CHEST, M.BACK, M.QUADRICEPS),
            INCLINE_CHEST,
            LAT_PULLDOWN,
            LEG_PRESS,
            GLUTE_BRIDGE,
            BICEPS,
        ),
    ),
    _template(
        "three-day-push-pull-legs",
        "Three-Day Push / Pull / Legs",
        "پوش / پول / پا سه روزه",
        "A classic three-day push, pull, and lower-body rotation.",
        "چرخش کلاسیک سه‌روزهٔ پوش، پول و پایین‌تنه.",
        3,
        Level.INTERMEDIATE,
        ("push_pull_legs", "classic", "balanced"),
        (Method.STANDARD,),
        _day(
            "Push",
            "پوش",
            (M.CHEST, M.SHOULDERS, M.TRICEPS),
            CHEST,
            SHOULDER_PRESS,
            LATERAL_RAISE,
            TRICEPS,
        ),
        _day(
            "Pull",
            "پول",
            (M.BACK, M.BICEPS),
            BACK_ROW,
            LAT_PULLDOWN,
            CABLE_PULLDOWN,
            BICEPS,
            HAMMER_CURL,
        ),
        _day(
            "Legs",
            "پا",
            (M.QUADRICEPS, M.HAMSTRINGS, M.GLUTES, M.CALVES),
            SQUAT,
            RDL,
            LEG_EXTENSION,
            CALF,
        ),
    ),
    _template(
        "three-day-chest-priority",
        "Three-Day Chest Priority",
        "تأکید سینه سه روزه",
        "A full-body rotation that gives chest two direct priority exposures.",
        "چرخش تمام‌بدن که به سینه دو مواجههٔ مستقیم با اولویت می‌دهد.",
        3,
        Level.INTERMEDIATE,
        ("full_body", "chest_priority", "weak_point"),
        (Method.STANDARD,),
        _day(
            "Chest + Quads",
            "سینه + چهارسر",
            (M.CHEST, M.QUADRICEPS),
            CHEST,
            INCLINE_CHEST,
            LEG_PRESS,
            LEG_EXTENSION,
        ),
        _day(
            "Back + Hamstrings",
            "زیربغل + همسترینگ",
            (M.BACK, M.HAMSTRINGS),
            BACK_ROW,
            LAT_PULLDOWN,
            RDL,
            LEG_CURL,
            BICEPS,
        ),
        _day(
            "Chest + Shoulders",
            "سینه + سرشانه",
            (M.CHEST, M.SHOULDERS),
            CABLE_FLY,
            CHEST,
            SHOULDER_PRESS,
            LATERAL_RAISE,
            TRICEPS,
        ),
    ),
    _template(
        "three-day-back-priority",
        "Three-Day Back Priority",
        "تأکید زیربغل سه روزه",
        "A full-body rotation that gives back two direct priority exposures.",
        "چرخش تمام‌بدن که به زیربغل دو مواجههٔ مستقیم با اولویت می‌دهد.",
        3,
        Level.INTERMEDIATE,
        ("full_body", "back_priority", "weak_point"),
        (Method.STANDARD,),
        _day(
            "Back + Quads",
            "زیربغل + چهارسر",
            (M.BACK, M.QUADRICEPS),
            BACK_ROW,
            LAT_PULLDOWN,
            LEG_PRESS,
            LEG_EXTENSION,
        ),
        _day(
            "Chest + Hamstrings",
            "سینه + همسترینگ",
            (M.CHEST, M.HAMSTRINGS),
            CHEST,
            INCLINE_CHEST,
            RDL,
            LEG_CURL,
        ),
        _day(
            "Back + Arms",
            "زیربغل + بازو",
            (M.BACK, M.BICEPS),
            CABLE_PULLDOWN,
            BACK_ROW,
            BICEPS,
            HAMMER_CURL,
            TRICEPS,
        ),
    ),
    _template(
        "three-day-full-body-drop-set",
        "Three-Day Full Body Drop Set",
        "تمام‌بدن دراپ‌ست سه روزه",
        "An advanced three-day structure that reserves drop sets for low-risk isolation work.",
        "ساختار پیشرفتهٔ سه‌روزه که دراپ‌ست را برای حرکات ایزولهٔ کم‌ریسک نگه می‌دارد.",
        3,
        Level.ADVANCED,
        ("full_body", "drop_set", "time_efficient"),
        (Method.STANDARD, Method.DROP_SET),
        _day(
            "Full Body A",
            "تمام‌بدن A",
            (M.CHEST, M.QUADRICEPS),
            CHEST,
            SQUAT,
            _slot(
                "leg-extension",
                (M.QUADRICEPS,),
                P.KNEE_EXTENSION,
                method=Method.DROP_SET,
                reps=(12, 15),
            ),
        ),
        _day(
            "Full Body B",
            "تمام‌بدن B",
            (M.BACK, M.HAMSTRINGS),
            BACK_ROW,
            RDL,
            _slot(
                "cable-curl", (M.BICEPS,), P.ELBOW_FLEXION, method=Method.DROP_SET, reps=(12, 15)
            ),
        ),
        _day(
            "Full Body C",
            "تمام‌بدن C",
            (M.SHOULDERS, M.GLUTES),
            SHOULDER_PRESS,
            GLUTE_BRIDGE,
            _slot(
                "dumbbell-lateral-raise",
                (M.SHOULDERS,),
                P.SHOULDER_ABDUCTION,
                method=Method.DROP_SET,
                reps=(12, 20),
            ),
        ),
    ),
    _template(
        "four-day-classic-body-part",
        "Four-Day Classic Body-Part Rotation",
        "تفکیک کلاسیک چهار روزه",
        "Direct-muscle pairing for lifters ready to separate upper-body targets "
        "across four sessions.",
        "جفت‌کردن عضلات هدف برای ورزشکاری که در چهار جلسه آمادهٔ تفکیک بالاتنه است.",
        4,
        Level.INTERMEDIATE,
        ("body_part_rotation", "classic", "direct_targets"),
        (Method.STANDARD,),
        _day(
            "Chest + Triceps",
            "سینه + پشت بازو",
            (M.CHEST, M.TRICEPS),
            CHEST,
            INCLINE_CHEST,
            CABLE_FLY,
            TRICEPS,
            PUSH_DOWN,
        ),
        _day(
            "Back + Biceps",
            "زیربغل + جلو بازو",
            (M.BACK, M.BICEPS),
            BACK_ROW,
            LAT_PULLDOWN,
            CABLE_PULLDOWN,
            BICEPS,
            HAMMER_CURL,
        ),
        _day(
            "Legs",
            "پا",
            (M.QUADRICEPS, M.HAMSTRINGS, M.GLUTES, M.CALVES),
            LEG_PRESS,
            RDL,
            LEG_EXTENSION,
            LEG_CURL,
            CALF,
        ),
        _day(
            "Shoulders + Traps",
            "سرشانه + کول",
            (M.SHOULDERS, M.TRAPS),
            SHOULDER_PRESS,
            LATERAL_RAISE,
            REAR_DELT,
            SHRUG,
        ),
    ),
    _template(
        "four-day-chest-priority",
        "Four-Day Chest Priority Rotation",
        "تفکیک چهار روزه با تأکید سینه",
        "A body-part rotation with two chest exposures while keeping arm work directly assigned.",
        "تفکیک عضلات با دو مواجههٔ سینه و حفظ تمرین مستقیم بازوها.",
        4,
        Level.INTERMEDIATE,
        ("body_part_rotation", "chest_priority", "weak_point"),
        (Method.STANDARD,),
        _day(
            "Chest + Triceps",
            "سینه + پشت بازو",
            (M.CHEST, M.TRICEPS),
            CHEST,
            INCLINE_CHEST,
            TRICEPS,
            PUSH_DOWN,
        ),
        _day(
            "Back + Biceps",
            "زیربغل + جلو بازو",
            (M.BACK, M.BICEPS),
            BACK_ROW,
            LAT_PULLDOWN,
            BICEPS,
            HAMMER_CURL,
        ),
        _day(
            "Legs",
            "پا",
            (M.QUADRICEPS, M.HAMSTRINGS, M.GLUTES, M.CALVES),
            LEG_PRESS,
            RDL,
            LEG_EXTENSION,
            CALF,
        ),
        _day(
            "Chest + Shoulders",
            "سینه + سرشانه",
            (M.CHEST, M.SHOULDERS),
            CABLE_FLY,
            CHEST,
            SHOULDER_PRESS,
            LATERAL_RAISE,
        ),
    ),
    _template(
        "four-day-back-priority",
        "Four-Day Back Priority Rotation",
        "تفکیک چهار روزه با تأکید زیربغل",
        "A body-part rotation with two direct back exposures and separated biceps work.",
        "تفکیک عضلات با دو مواجههٔ مستقیم زیربغل و جلو بازوی جداشده.",
        4,
        Level.INTERMEDIATE,
        ("body_part_rotation", "back_priority", "weak_point"),
        (Method.STANDARD,),
        _day(
            "Chest + Triceps",
            "سینه + پشت بازو",
            (M.CHEST, M.TRICEPS),
            CHEST,
            INCLINE_CHEST,
            TRICEPS,
            PUSH_DOWN,
        ),
        _day(
            "Back + Biceps",
            "زیربغل + جلو بازو",
            (M.BACK, M.BICEPS),
            BACK_ROW,
            LAT_PULLDOWN,
            CABLE_PULLDOWN,
            BICEPS,
        ),
        _day("Legs", "پا", (M.QUADRICEPS, M.HAMSTRINGS, M.GLUTES), SQUAT, RDL, LEG_CURL, CALF),
        _day(
            "Back + Shoulders",
            "زیربغل + سرشانه",
            (M.BACK, M.SHOULDERS),
            BACK_ROW,
            LAT_PULLDOWN,
            LATERAL_RAISE,
            REAR_DELT,
        ),
    ),
    _template(
        "four-day-quad-hamstring-split",
        "Four-Day Quad / Hamstring Split",
        "تفکیک چهار روزهٔ چهارسر / همسترینگ",
        "An advanced upper/lower variant that separates knee-dominant and posterior-chain work.",
        "گونهٔ پیشرفتهٔ بالاتنه/پایین‌تنه که چهارسر و زنجیرهٔ خلفی را جدا می‌کند.",
        4,
        Level.ADVANCED,
        ("upper_lower", "quad_priority", "hamstrings_glutes"),
        (Method.STANDARD,),
        _day(
            "Chest + Back",
            "سینه + زیربغل",
            (M.CHEST, M.BACK),
            CHEST,
            BACK_ROW,
            INCLINE_CHEST,
            LAT_PULLDOWN,
        ),
        _day(
            "Quadriceps + Calves",
            "چهارسر + ساق",
            (M.QUADRICEPS, M.CALVES),
            LEG_PRESS,
            SQUAT,
            LEG_EXTENSION,
            CALF,
        ),
        _day(
            "Shoulders + Arms",
            "سرشانه + بازو",
            (M.SHOULDERS, M.BICEPS, M.TRICEPS),
            SHOULDER_PRESS,
            LATERAL_RAISE,
            BICEPS,
            TRICEPS,
        ),
        _day(
            "Hamstrings + Glutes",
            "همسترینگ + باسن",
            (M.HAMSTRINGS, M.GLUTES),
            RDL,
            LEG_CURL,
            GLUTE_BRIDGE,
            LUNGE,
        ),
    ),
    _template(
        "four-day-phul",
        "Four-Day Power Hypertrophy Upper / Lower",
        "بالا / پایین قدرت و هایپرتروفی چهار روزه",
        "A higher-skill four-day upper/lower pattern with compound and hypertrophy exposures.",
        "الگوی بالاتنه/پایین‌تنهٔ چهارروزه با ترکیب حرکات پایه و هایپرتروفی.",
        4,
        Level.ADVANCED,
        ("upper_lower", "strength_hypertrophy", "classic"),
        (Method.STANDARD,),
        _day(
            "Upper Compound",
            "بالاتنه چندمفصلی",
            (M.CHEST, M.BACK, M.SHOULDERS),
            CHEST,
            BACK_ROW,
            SHOULDER_PRESS,
            BICEPS,
        ),
        _day(
            "Lower Compound",
            "پایین‌تنه چندمفصلی",
            (M.QUADRICEPS, M.HAMSTRINGS, M.GLUTES),
            LEG_PRESS,
            RDL,
            LUNGE,
            CALF,
        ),
        _day(
            "Upper Hypertrophy",
            "هایپرتروفی بالاتنه",
            (M.CHEST, M.BACK, M.SHOULDERS, M.ARMS if False else M.BICEPS),
            INCLINE_CHEST,
            LAT_PULLDOWN,
            LATERAL_RAISE,
            BICEPS,
            TRICEPS,
        ),
        _day(
            "Lower Hypertrophy",
            "هایپرتروفی پایین‌تنه",
            (M.QUADRICEPS, M.HAMSTRINGS, M.GLUTES, M.CALVES),
            SQUAT,
            LEG_EXTENSION,
            LEG_CURL,
            GLUTE_BRIDGE,
            CALF,
        ),
    ),
    _template(
        "five-day-classic-body-part",
        "Five-Day Classic Body-Part Rotation",
        "تفکیک کلاسیک پنج روزه",
        "A conventional five-day rotation with one clear direct target group per session.",
        "چرخش متعارف پنج‌روزه با گروه عضلانی هدف روشن در هر جلسه.",
        5,
        Level.INTERMEDIATE,
        ("body_part_rotation", "classic", "balanced"),
        (Method.STANDARD,),
        _day("Chest", "سینه", (M.CHEST,), CHEST, INCLINE_CHEST, CABLE_FLY),
        _day("Back", "زیربغل", (M.BACK,), BACK_ROW, LAT_PULLDOWN, CABLE_PULLDOWN),
        _day(
            "Legs",
            "پا",
            (M.QUADRICEPS, M.HAMSTRINGS, M.GLUTES, M.CALVES),
            LEG_PRESS,
            RDL,
            LEG_EXTENSION,
            LEG_CURL,
            CALF,
        ),
        _day(
            "Shoulders + Traps",
            "سرشانه + کول",
            (M.SHOULDERS, M.TRAPS),
            SHOULDER_PRESS,
            LATERAL_RAISE,
            REAR_DELT,
            SHRUG,
        ),
        _day("Arms", "بازو", (M.BICEPS, M.TRICEPS), BICEPS, HAMMER_CURL, TRICEPS, PUSH_DOWN),
    ),
    _template(
        "five-day-ppl-upper-lower",
        "Five-Day Push Pull Legs Upper Lower",
        "پوش پول پا بالاتنه پایین‌تنه پنج روزه",
        "A five-day hybrid that adds an upper/lower exposure after a push-pull-legs base.",
        "ترکیب پنج‌روزه که بعد از پایهٔ پوش پول پا، یک مواجههٔ بالاتنه/پایین‌تنه اضافه می‌کند.",
        5,
        Level.INTERMEDIATE,
        ("push_pull_legs", "upper_lower", "balanced"),
        (Method.STANDARD,),
        _day("Push", "پوش", (M.CHEST, M.SHOULDERS, M.TRICEPS), CHEST, SHOULDER_PRESS, TRICEPS),
        _day("Pull", "پول", (M.BACK, M.BICEPS), BACK_ROW, LAT_PULLDOWN, BICEPS),
        _day("Legs", "پا", (M.QUADRICEPS, M.HAMSTRINGS, M.GLUTES, M.CALVES), SQUAT, RDL, CALF),
        _day(
            "Upper",
            "بالاتنه",
            (M.CHEST, M.BACK, M.SHOULDERS),
            INCLINE_CHEST,
            CABLE_PULLDOWN,
            LATERAL_RAISE,
            HAMMER_CURL,
        ),
        _day(
            "Lower",
            "پایین‌تنه",
            (M.QUADRICEPS, M.HAMSTRINGS, M.GLUTES),
            LEG_PRESS,
            LEG_EXTENSION,
            LEG_CURL,
            GLUTE_BRIDGE,
        ),
    ),
    _template(
        "five-day-chest-specialization",
        "Five-Day Chest Specialization",
        "تخصصی سینه پنج روزه",
        "Extra direct chest exposure placed early in two weekly sessions "
        "for a chest priority block.",
        "مواجههٔ مستقیم اضافهٔ سینه در ابتدای دو جلسهٔ هفتگی برای دورهٔ اولویت سینه.",
        5,
        Level.ADVANCED,
        ("body_part_rotation", "chest_priority", "specialization"),
        (Method.STANDARD,),
        _day(
            "Chest + Triceps",
            "سینه + پشت بازو",
            (M.CHEST, M.TRICEPS),
            CHEST,
            INCLINE_CHEST,
            CABLE_FLY,
            TRICEPS,
        ),
        _day(
            "Back + Biceps", "زیربغل + جلو بازو", (M.BACK, M.BICEPS), BACK_ROW, LAT_PULLDOWN, BICEPS
        ),
        _day(
            "Legs",
            "پا",
            (M.QUADRICEPS, M.HAMSTRINGS, M.GLUTES),
            LEG_PRESS,
            RDL,
            LEG_EXTENSION,
            LEG_CURL,
        ),
        _day(
            "Chest + Shoulders",
            "سینه + سرشانه",
            (M.CHEST, M.SHOULDERS),
            CHEST,
            CABLE_FLY,
            SHOULDER_PRESS,
            LATERAL_RAISE,
        ),
        _day(
            "Arms + Calves",
            "بازو + ساق",
            (M.BICEPS, M.TRICEPS, M.CALVES),
            HAMMER_CURL,
            PUSH_DOWN,
            TRICEPS,
            CALF,
        ),
    ),
    _template(
        "five-day-back-specialization",
        "Five-Day Back Specialization",
        "تخصصی زیربغل پنج روزه",
        "Extra direct back exposure without moving biceps into every back session.",
        "مواجههٔ مستقیم اضافهٔ زیربغل بدون قراردادن جلو بازو در تمام جلسات پشت.",
        5,
        Level.ADVANCED,
        ("body_part_rotation", "back_priority", "specialization"),
        (Method.STANDARD,),
        _day(
            "Chest + Triceps",
            "سینه + پشت بازو",
            (M.CHEST, M.TRICEPS),
            CHEST,
            INCLINE_CHEST,
            TRICEPS,
            PUSH_DOWN,
        ),
        _day(
            "Back + Biceps",
            "زیربغل + جلو بازو",
            (M.BACK, M.BICEPS),
            BACK_ROW,
            LAT_PULLDOWN,
            CABLE_PULLDOWN,
            BICEPS,
        ),
        _day(
            "Legs",
            "پا",
            (M.QUADRICEPS, M.HAMSTRINGS, M.GLUTES),
            SQUAT,
            RDL,
            LEG_EXTENSION,
            LEG_CURL,
        ),
        _day(
            "Back + Rear Delts",
            "زیربغل + پشت سرشانه",
            (M.BACK, M.SHOULDERS),
            BACK_ROW,
            LAT_PULLDOWN,
            REAR_DELT,
            CABLE_PULLDOWN,
        ),
        _day(
            "Shoulders + Arms",
            "سرشانه + بازو",
            (M.SHOULDERS, M.BICEPS, M.TRICEPS),
            SHOULDER_PRESS,
            LATERAL_RAISE,
            HAMMER_CURL,
            PUSH_DOWN,
        ),
    ),
    _template(
        "five-day-posterior-chain-superset",
        "Five-Day Posterior Chain Supersets",
        "سوپرست زنجیرهٔ خلفی پنج روزه",
        "An advanced posterior-chain emphasis with compatible isolation supersets.",
        "تأکید پیشرفتهٔ زنجیرهٔ خلفی با سوپرست‌های سازگارِ ایزوله.",
        5,
        Level.ADVANCED,
        ("hamstrings_glutes", "superset", "time_efficient"),
        (Method.STANDARD, Method.SUPERSET),
        _day(
            "Chest + Triceps",
            "سینه + پشت بازو",
            (M.CHEST, M.TRICEPS),
            CHEST,
            INCLINE_CHEST,
            TRICEPS,
        ),
        _day(
            "Back + Biceps", "زیربغل + جلو بازو", (M.BACK, M.BICEPS), BACK_ROW, LAT_PULLDOWN, BICEPS
        ),
        _day(
            "Quadriceps + Calves",
            "چهارسر + ساق",
            (M.QUADRICEPS, M.CALVES),
            LEG_PRESS,
            LEG_EXTENSION,
            _slot("standing-calf-raise", (M.CALVES,), P.CALF_RAISE, method=Method.SUPERSET),
        ),
        _day(
            "Hamstrings + Glutes",
            "همسترینگ + باسن",
            (M.HAMSTRINGS, M.GLUTES),
            RDL,
            LEG_CURL,
            GLUTE_BRIDGE,
            LUNGE,
        ),
        _day(
            "Shoulders + Rear Delts",
            "سرشانه + پشت سرشانه",
            (M.SHOULDERS,),
            SHOULDER_PRESS,
            _slot(
                "dumbbell-lateral-raise",
                (M.SHOULDERS,),
                P.SHOULDER_ABDUCTION,
                method=Method.SUPERSET,
            ),
            _slot("rear-delt-fly", (M.SHOULDERS,), P.HORIZONTAL_PULL, method=Method.SUPERSET),
        ),
    ),
    _template(
        "six-day-ppl-twice",
        "Six-Day Push Pull Legs Twice",
        "پوش پول پا دوبار در هفته",
        "The conventional six-day PPL rotation with direct exposure repeated twice.",
        "چرخش متعارف شش‌روزهٔ پوش پول پا با دو مواجههٔ مستقیم برای هر الگو.",
        6,
        Level.INTERMEDIATE,
        ("push_pull_legs", "classic", "frequency_two"),
        (Method.STANDARD,),
        _day("Push A", "پوش A", (M.CHEST, M.SHOULDERS, M.TRICEPS), CHEST, SHOULDER_PRESS, TRICEPS),
        _day("Pull A", "پول A", (M.BACK, M.BICEPS), BACK_ROW, LAT_PULLDOWN, BICEPS),
        _day("Legs A", "پا A", (M.QUADRICEPS, M.HAMSTRINGS, M.GLUTES), SQUAT, RDL, CALF),
        _day(
            "Push B",
            "پوش B",
            (M.CHEST, M.SHOULDERS, M.TRICEPS),
            INCLINE_CHEST,
            LATERAL_RAISE,
            PUSH_DOWN,
        ),
        _day("Pull B", "پول B", (M.BACK, M.BICEPS), CABLE_PULLDOWN, BACK_ROW, HAMMER_CURL),
        _day(
            "Legs B",
            "پا B",
            (M.QUADRICEPS, M.HAMSTRINGS, M.GLUTES),
            LEG_PRESS,
            LEG_EXTENSION,
            LEG_CURL,
            GLUTE_BRIDGE,
        ),
    ),
    _template(
        "six-day-ppl-volume",
        "Six-Day PPL Volume Rotation",
        "چرخش حجمی پوش پول پا شش روزه",
        "A higher-volume PPL rotation that spreads direct work across "
        "two push, pull, and leg days.",
        "چرخش حجمی پوش پول پا که کار مستقیم را در دو روز پوش، پول و پا پخش می‌کند.",
        6,
        Level.ADVANCED,
        ("push_pull_legs", "hypertrophy", "volume"),
        (Method.STANDARD,),
        _day(
            "Push Chest", "پوش سینه", (M.CHEST, M.TRICEPS), CHEST, INCLINE_CHEST, CABLE_FLY, TRICEPS
        ),
        _day("Pull Width", "پول عرض پشت", (M.BACK, M.BICEPS), LAT_PULLDOWN, CABLE_PULLDOWN, BICEPS),
        _day(
            "Legs Quadriceps",
            "پا چهارسر",
            (M.QUADRICEPS, M.CALVES),
            LEG_PRESS,
            SQUAT,
            LEG_EXTENSION,
            CALF,
        ),
        _day(
            "Push Shoulders",
            "پوش سرشانه",
            (M.SHOULDERS, M.TRICEPS),
            SHOULDER_PRESS,
            LATERAL_RAISE,
            REAR_DELT,
            PUSH_DOWN,
        ),
        _day(
            "Pull Thickness",
            "پول ضخامت پشت",
            (M.BACK, M.BICEPS),
            BACK_ROW,
            LAT_PULLDOWN,
            HAMMER_CURL,
        ),
        _day(
            "Legs Posterior",
            "پا زنجیرهٔ خلفی",
            (M.HAMSTRINGS, M.GLUTES),
            RDL,
            LEG_CURL,
            GLUTE_BRIDGE,
            LUNGE,
        ),
    ),
    _template(
        "six-day-chest-back-legs-shoulders-arms-legs",
        "Six-Day Body-Part Rotation",
        "تفکیک عضلات شش روزه",
        "A classic body-part rotation for advanced lifters who recover well "
        "from frequent sessions.",
        "تفکیک کلاسیک عضلات برای ورزشکار پیشرفته با ریکاوری مناسب از جلسات پرتعداد.",
        6,
        Level.ADVANCED,
        ("body_part_rotation", "classic", "high_frequency"),
        (Method.STANDARD,),
        _day("Chest", "سینه", (M.CHEST,), CHEST, INCLINE_CHEST, CABLE_FLY),
        _day("Back", "زیربغل", (M.BACK,), BACK_ROW, LAT_PULLDOWN, CABLE_PULLDOWN),
        _day(
            "Quadriceps + Calves",
            "چهارسر + ساق",
            (M.QUADRICEPS, M.CALVES),
            LEG_PRESS,
            LEG_EXTENSION,
            CALF,
        ),
        _day(
            "Shoulders + Traps",
            "سرشانه + کول",
            (M.SHOULDERS, M.TRAPS),
            SHOULDER_PRESS,
            LATERAL_RAISE,
            REAR_DELT,
            SHRUG,
        ),
        _day("Arms", "بازو", (M.BICEPS, M.TRICEPS), BICEPS, HAMMER_CURL, TRICEPS, PUSH_DOWN),
        _day(
            "Hamstrings + Glutes",
            "همسترینگ + باسن",
            (M.HAMSTRINGS, M.GLUTES),
            RDL,
            LEG_CURL,
            GLUTE_BRIDGE,
            LUNGE,
        ),
    ),
    _template(
        "six-day-chest-priority",
        "Six-Day Chest Priority",
        "تأکید سینه شش روزه",
        "A specialization block with three controlled chest exposures separated by other targets.",
        "دورهٔ تخصصی با سه مواجههٔ کنترل‌شدهٔ سینه که با اهداف دیگر جدا شده‌اند.",
        6,
        Level.ADVANCED,
        ("body_part_rotation", "chest_priority", "specialization"),
        (Method.STANDARD,),
        _day("Chest Heavy", "سینه سنگین", (M.CHEST,), CHEST, INCLINE_CHEST, CABLE_FLY),
        _day(
            "Back + Biceps", "زیربغل + جلو بازو", (M.BACK, M.BICEPS), BACK_ROW, LAT_PULLDOWN, BICEPS
        ),
        _day(
            "Legs",
            "پا",
            (M.QUADRICEPS, M.HAMSTRINGS, M.GLUTES),
            LEG_PRESS,
            RDL,
            LEG_EXTENSION,
            LEG_CURL,
        ),
        _day("Chest Volume", "سینه حجمی", (M.CHEST,), INCLINE_CHEST, CABLE_FLY, CHEST),
        _day(
            "Shoulders + Triceps",
            "سرشانه + پشت بازو",
            (M.SHOULDERS, M.TRICEPS),
            SHOULDER_PRESS,
            LATERAL_RAISE,
            TRICEPS,
        ),
        _day(
            "Chest Pump + Calves",
            "پمپ سینه + ساق",
            (M.CHEST, M.CALVES),
            CABLE_FLY,
            INCLINE_CHEST,
            CALF,
        ),
    ),
    _template(
        "six-day-back-priority",
        "Six-Day Back Priority",
        "تأکید زیربغل شش روزه",
        "A specialization block with three back exposures separated by push and lower-body work.",
        "دورهٔ تخصصی با سه مواجههٔ زیربغل که با پوش و پایین‌تنه جدا شده‌اند.",
        6,
        Level.ADVANCED,
        ("body_part_rotation", "back_priority", "specialization"),
        (Method.STANDARD,),
        _day("Back Width", "عرض زیربغل", (M.BACK,), LAT_PULLDOWN, CABLE_PULLDOWN, BACK_ROW),
        _day(
            "Chest + Triceps",
            "سینه + پشت بازو",
            (M.CHEST, M.TRICEPS),
            CHEST,
            INCLINE_CHEST,
            TRICEPS,
        ),
        _day(
            "Legs",
            "پا",
            (M.QUADRICEPS, M.HAMSTRINGS, M.GLUTES),
            SQUAT,
            RDL,
            LEG_EXTENSION,
            LEG_CURL,
        ),
        _day("Back Thickness", "ضخامت زیربغل", (M.BACK,), BACK_ROW, LAT_PULLDOWN, CABLE_PULLDOWN),
        _day(
            "Shoulders + Biceps",
            "سرشانه + جلو بازو",
            (M.SHOULDERS, M.BICEPS),
            SHOULDER_PRESS,
            LATERAL_RAISE,
            BICEPS,
        ),
        _day(
            "Back Pump + Calves",
            "پمپ زیربغل + ساق",
            (M.BACK, M.CALVES),
            CABLE_PULLDOWN,
            BACK_ROW,
            CALF,
        ),
    ),
)
