"""add_superset_fields_to_template_slot

Revision ID: 375f20e220a9
Revises: 20260826_110
Create Date: 2026-08-26 10:47:03.819827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '375f20e220a9'
down_revision: Union[str, Sequence[str], None] = '20260826_110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_program_template_slots', sa.Column('superset_exercise_id', sa.Uuid(), nullable=True))
    op.add_column('training_program_template_slots', sa.Column('superset_exercise_slug_hint', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_training_program_template_slots_superset_exercise_id'), 'training_program_template_slots', ['superset_exercise_id'], unique=False)
    op.create_foreign_key(op.f('fk_training_program_template_slots_superset_exercise_id_exercises'), 'training_program_template_slots', 'exercises', ['superset_exercise_id'], ['id'], ondelete='SET NULL')
    
    op.execute(
        """
        WITH superset_pairs AS (
            SELECT
                s1.id AS slot1_id,
                s2.id AS slot2_id,
                s2.exercise_id AS superset_exercise_id,
                s2.exercise_slug_hint AS superset_exercise_slug_hint
            FROM training_program_template_slots s1
            JOIN training_program_template_slots s2
              ON s1.template_day_id = s2.template_day_id
             AND s1.superset_group = s2.superset_group
             AND s1.slot_order = s2.slot_order - 1
            WHERE s1.intensity_method = 'superset'
              AND s2.intensity_method = 'superset'
              AND s1.superset_group IS NOT NULL
        )
        UPDATE training_program_template_slots
        SET superset_exercise_id = superset_pairs.superset_exercise_id,
            superset_exercise_slug_hint = superset_pairs.superset_exercise_slug_hint
        FROM superset_pairs
        WHERE training_program_template_slots.id = superset_pairs.slot1_id;
        """
    )
    
    op.execute(
        """
        DELETE FROM training_program_template_slots s2
        USING training_program_template_slots s1
        WHERE s1.template_day_id = s2.template_day_id
          AND s1.superset_group = s2.superset_group
          AND s1.slot_order = s2.slot_order - 1
          AND s1.intensity_method = 'superset'
          AND s2.intensity_method = 'superset'
          AND s1.superset_group IS NOT NULL;
        """
    )
    
    op.execute(
        """
        WITH numbered AS (
            SELECT id,
                   row_number() OVER (PARTITION BY template_day_id ORDER BY slot_order) as new_order
            FROM training_program_template_slots
        )
        UPDATE training_program_template_slots
        SET slot_order = numbered.new_order
        FROM numbered
        WHERE training_program_template_slots.id = numbered.id;
        """
    )
    
    op.create_check_constraint('ck_training_program_template_slots_superset_validity', 'training_program_template_slots', "(intensity_method = 'superset' AND superset_exercise_id IS NOT NULL AND exercise_id != superset_exercise_id AND superset_exercise_slug_hint IS NOT NULL) OR (intensity_method != 'superset' AND superset_exercise_id IS NULL AND superset_exercise_slug_hint IS NULL)")
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_training_program_template_slots_superset_validity', 'training_program_template_slots')
    op.drop_constraint(op.f('fk_training_program_template_slots_superset_exercise_id_exercises'), 'training_program_template_slots', type_='foreignkey')
    op.drop_index(op.f('ix_training_program_template_slots_superset_exercise_id'), table_name='training_program_template_slots')
    op.drop_column('training_program_template_slots', 'superset_exercise_slug_hint')
    op.drop_column('training_program_template_slots', 'superset_exercise_id')
    # ### end Alembic commands ###

