"""add exercise media assets

Revision ID: 9a0e535a9e11
Revises: 20260728_07
Create Date: 2026-07-29 23:10:11.420250

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a0e535a9e11"
down_revision: str | Sequence[str] | None = "20260728_07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise_media_assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("exercise_id", sa.Uuid(), nullable=False),
        sa.Column(
            "presentation",
            sa.Enum(
                "male",
                "female",
                name="ck_exercise_media_assets_presentation_values",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum(
                "video",
                "thumbnail",
                name="ck_exercise_media_assets_role_values",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("media_path", sa.String(length=255), nullable=False),
        sa.Column(
            "media_type",
            sa.Enum(
                "image",
                "animated_webp",
                "gif",
                "video",
                "placeholder",
                name="ck_exercise_media_assets_media_type_values",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("media_source_url", sa.String(length=500), nullable=True),
        sa.Column("media_license", sa.String(length=120), nullable=True),
        sa.Column("media_attribution", sa.String(length=500), nullable=True),
        sa.CheckConstraint(
            "(role = 'video' AND media_type = 'video')"
            " OR (role = 'thumbnail' AND media_type = 'image')",
            name="ck_exercise_media_assets_role_media_type",
        ),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "exercise_id",
            "presentation",
            "role",
            name="uq_exercise_media_assets_exercise_presentation_role",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exercise_media_assets")
    # ### end Alembic commands ###
