import type {
  BodyRegion,
  Difficulty,
  Equipment,
  ExerciseLabel,
  ExerciseType,
  MuscleFocus,
  MuscleGroup,
} from "@fitician/core/exercises";

import type { MobileLanguage } from "../ui/rtl";

export const exerciseCopy = {
  advancedFilters: "فیلترهای پیشرفته",
  allExercises: "همه حرکات",
  allMuscleFocuses: "همه بخش‌های این عضله",
  bodyRegion: "ناحیه بدن",
  bodyRegions: {
    core: "میان‌تنه",
    lower_body: "پایین‌تنه",
    upper_body: "بالاتنه",
  } satisfies Record<BodyRegion, string>,
  bodyRegionIntro: "ابتدا ناحیه‌ای را که می‌خواهی تمرین کنی انتخاب کن.",
  catalogIntro: "حرکت‌ها و راهنماهای تأییدشدهٔ تمرینی را پیدا کن.",
  categoriesError: "دسته‌بندی حرکات دریافت نشد.",
  categoriesLoading: "در حال دریافت دسته‌بندی‌ها…",
  clearFilters: "پاک کردن فیلترها",
  contentType: "نوع محتوا",
  contentTypes: {
    exercise: "حرکت‌ها",
    guide: "راهنماها",
  },
  difficulty: "سطح سختی",
  difficulties: {
    advanced: "پیشرفته",
    beginner: "مبتدی",
    intermediate: "متوسط",
  } satisfies Record<Difficulty, string>,
  equipment: "تجهیزات",
  equipments: {
    barbell: "هالتر",
    bench: "نیمکت",
    bodyweight: "وزن بدن",
    cable: "کابل",
    dumbbell: "دمبل",
    machine: "دستگاه",
    other: "سایر",
    pull_up_bar: "میله بارفیکس",
    resistance_band: "کش مقاومتی",
  } satisfies Record<Equipment, string>,
  error: "حرکات دریافت نشدند.",
  filters: "فیلترها",
  focus: "تمرکز عضلانی",
  focusIntro: "اگر می‌خواهی، بخش دقیق عضله را انتخاب کن.",
  fullBody: "تمام بدن",
  guides: "راهنماها",
  library: "کتابخانه حرکات",
  loading: "در حال دریافت حرکات…",
  mediaUnavailable: "رسانهٔ این حرکت در دسترس نیست.",
  mobility: "تحرک و کشش",
  moreFilters: "فیلترهای بیشتر",
  muscle: "عضله هدف",
  muscleIntro: "عضله هدف را انتخاب کن تا فهرست دقیق‌تر شود.",
  noResults: "حرکتی با این فیلترها پیدا نشد.",
  noSelection: "برای دیدن حرکت‌ها، یک عضله یا فیلتر ویژه انتخاب کن.",
  notSpecified: "مشخص نشده",
  needsReview: "نیازمند بازبینی",
  nextPage: "صفحه بعد",
  primaryMuscleLabel: "عضله اصلی",
  previousPage: "صفحه قبل",
  retry: "تلاش دوباره",
  resultsTitle: "نتایج حرکات",
  search: "جستجوی حرکت",
  searchPlaceholder: "مثلاً پرس سینه",
  selectMusclePrompt: "حالا عضله هدفت را انتخاب کن.",
  selectRegionPrompt: "برای شروع، بالاتنه، پایین‌تنه یا میان‌تنه را انتخاب کن.",
  safety: "نکات ایمنی",
  secondaryMuscles: "عضلات کمکی",
  specialFilters: "فیلترهای ویژه",
  stale: "در حال به‌روزرسانی فهرست…",
  trainingOnly: "این کتابخانه برای بخش تمرین است.",
  unknownExercise: "این حرکت پیدا نشد.",
  instructions: "راهنمای اجرا",
  muscleFocusLabel: "بخش هدف",
  viewExercise: "مشاهده حرکت",
  viewGuide: "مشاهده راهنما",
  muscles: {
    abs: "شکم",
    abductors: "بیرون پا",
    adductors: "داخل پا",
    back: "پشت و زیر بغل",
    biceps: "جلو بازو",
    calves: "ساق",
    chest: "سینه",
    glutes: "باسن",
    hamstrings: "پشت پا",
    legs: "کل پا",
    lower_back: "کمر",
    neck: "گردن",
    obliques: "پهلو",
    quadriceps: "جلو پا",
    shoulders: "سرشانه",
    traps: "کول",
    triceps: "پشت بازو",
    forearms: "ساعد",
  } satisfies Record<MuscleGroup, string>,
  muscleFocuses: {
    adductor_mobility: "تحرک داخل پا",
    anti_extension: "ضد بازشدن کمر",
    anti_rotation: "ضد چرخش",
    biceps_brachii: "دوسر بازویی",
    brachialis_brachioradialis: "بازویی و بازویی‌زندزبرین",
    forearm_extensors: "بازکننده‌های ساعد",
    forearm_flexors: "خم‌کننده‌های ساعد",
    front_delt: "سرشانه جلویی",
    general_back: "پشت عمومی",
    general_biceps: "جلو بازوی عمومی",
    general_calves: "ساق عمومی",
    general_chest: "سینه عمومی",
    general_forearms: "ساعد عمومی",
    general_quadriceps: "جلوران عمومی",
    general_shoulders: "سرشانه عمومی",
    general_triceps: "پشت بازوی عمومی",
    glute_max: "سرینی بزرگ",
    glute_medius_minimus: "سرینی میانی و کوچک",
    gastrocnemius: "دوقلو",
    hamstrings_hip_extension: "بازشدن لگن با پشت پا",
    hamstrings_knee_flexion: "خم‌کردن زانو با پشت پا",
    hip_adduction: "نزدیک‌کردن لگن",
    hip_flexion_posterior_tilt: "خم‌کردن لگن و چرخش لگن",
    lateral_flexion: "خم‌شدن جانبی",
    lateral_delt: "سرشانه میانی",
    lats: "زیر بغل",
    lower_chest: "زیر سینه",
    lower_back: "پایین پشت",
    lumbar_erectors: "راست‌کننده‌های کمر",
    mid_back_rhomboids: "میان پشت و لوزی‌ها",
    mid_chest: "وسط سینه",
    mid_lower_traps: "کول میانی و پایینی",
    neck_flexion: "خم‌کردن گردن",
    neck_lateral_extension: "بازشدن جانبی گردن",
    rear_delt: "سرشانه پشتی",
    rectus_femoris: "راست‌رانی",
    soleus: "نعلی",
    thoracic_mobility: "تحرک پشت سینه‌ای",
    trunk_flexion: "خم‌کردن تنه",
    trunk_rotation: "چرخش تنه",
    triceps_lateral_medial_heads: "سرهای خارجی و میانی پشت بازو",
    triceps_long_head: "سر بلند پشت بازو",
    upper_back: "بالای پشت",
    upper_chest: "بالاسینه",
    upper_traps: "کول بالایی",
    vasti: "پهن‌ها",
  } satisfies Record<MuscleFocus, string>,
  exerciseTypes: {
    compound: "چندمفصلی",
    core: "میان‌تنه",
    isolation: "تک‌مفصلی",
    mobility: "تحرک",
    other: "سایر",
  } satisfies Record<ExerciseType, string>,
  labels: {
    cardio: "هوازی",
    full_body: "تمام بدن",
  } satisfies Record<ExerciseLabel, string>,
} as const;

export function exerciseTitle(
  nameFa: string,
  nameEn: string,
  language: MobileLanguage = "fa",
): string {
  const localizedName = (language === "en" ? nameEn : nameFa).trim();
  if (localizedName) return localizedName;
  return (language === "en" ? nameFa : nameEn).trim();
}

export function exerciseSecondaryTitle(nameFa: string, nameEn: string): string {
  return nameEn.trim() || nameFa;
}

export function formatExerciseCount(value: number): string {
  return new Intl.NumberFormat("fa-IR").format(value);
}
