with open("frontend/src/features/admin/admin.css", "a") as f:
    f.write("\n")
    f.write(".admin-method-selector {\n")
    f.write("  display: flex;\n")
    f.write("  gap: 1rem;\n")
    f.write("  margin-bottom: 0.5rem;\n")
    f.write("}\n")
    f.write(".admin-method-selector label {\n")
    f.write("  display: flex;\n")
    f.write("  align-items: center;\n")
    f.write("  gap: 0.25rem;\n")
    f.write("  cursor: pointer;\n")
    f.write("}\n")
    f.write(".admin-slot-picker-group {\n")
    f.write("  display: flex;\n")
    f.write("  align-items: center;\n")
    f.write("  justify-content: space-between;\n")
    f.write("  padding: 0.5rem;\n")
    f.write("  border: 1px solid var(--fitsho-border);\n")
    f.write("  border-radius: var(--fitsho-radius);\n")
    f.write("  background-color: var(--fitsho-surface);\n")
    f.write("}\n")
    f.write(".admin-slot-picker-group button {\n")
    f.write("  background: var(--fitsho-primary);\n")
    f.write("  color: white;\n")
    f.write("  border: none;\n")
    f.write("  padding: 0.25rem 0.75rem;\n")
    f.write("  border-radius: 4px;\n")
    f.write("  cursor: pointer;\n")
    f.write("}\n")
    f.write(".admin-badge {\n")
    f.write("  display: inline-block;\n")
    f.write("  padding: 0.125rem 0.375rem;\n")
    f.write("  border-radius: 4px;\n")
    f.write("  font-size: 0.75rem;\n")
    f.write("  font-weight: 600;\n")
    f.write("  margin-left: 0.5rem;\n")
    f.write("}\n")
    f.write(".admin-badge--superset {\n")
    f.write("  background: #e0f2fe;\n")
    f.write("  color: #0369a1;\n")
    f.write("}\n")
    f.write(".admin-badge--drop-set {\n")
    f.write("  background: #fce7f3;\n")
    f.write("  color: #be185d;\n")
    f.write("}\n")
