import re
with open("backend/alembic/versions/375f20e220a9_add_superset_fields_to_template_slot.py", "r") as f:
    content = f.read()

# Remove all drop/create check constraints except the new one
content = re.sub(r'    op\.drop_check_constraint\([^,]+, \'[a-z_]+\'(, type_=\'check\')?\)\n', '', content)
content = re.sub(r'    op\.create_check_constraint\(op\.f\(\'ck_[a-z_]+\'\), \'[a-z_]+\', "[^"]+"\)\n', '', content)

# Keep the one we care about
# Oh wait, we removed it along with others. Let's just put it back.
content = content.replace(
    "# ### commands auto generated by Alembic - please adjust! ###\n",
    "# ### commands auto generated by Alembic - please adjust! ###\n"
    "    op.create_check_constraint('ck_training_program_template_slots_superset_validity', 'training_program_template_slots', \"(intensity_method = 'superset' AND superset_exercise_id IS NOT NULL AND exercise_id != superset_exercise_id AND superset_exercise_slug_hint IS NOT NULL) OR (intensity_method != 'superset' AND superset_exercise_id IS NULL AND superset_exercise_slug_hint IS NULL)\")\n"
)
content = content.replace(
    "# ### commands auto generated by Alembic - please adjust! ###\n",
    "# ### commands auto generated by Alembic - please adjust! ###\n"
    "    op.drop_constraint('ck_training_program_template_slots_superset_validity', 'training_program_template_slots')\n"
)

# wait, I'll just write a cleaner script to inject the logic exactly.
