import { readFile } from "node:fs/promises";
import { expect, it } from "vitest";

it("uses the web weekly nutrition plan hierarchy", async () => {
  const route = await readFile(new URL("../app/(member)/member/nutrition-plan.tsx", import.meta.url), "utf8");
  const source = await readFile(new URL("./NutritionPlanSection.tsx", import.meta.url), "utf8");
  const shopping = await readFile(new URL("./NutritionShoppingList.tsx", import.meta.url), "utf8");

  expect(route).toContain("PageHeading");
  expect(route).not.toContain("ScreenHeader");
  expect(source).toContain("برنامه هفتگی");
  expect(source).toContain("برنامه غذایی تو");
  expect(source).toContain("🧑‍⚕️");
  expect(source).toContain("در انتظار بررسی پزشک");
  expect(source).toContain("تأییدشده توسط پزشک");
  expect(source).toContain("📋");
  expect(source).toContain("قیمت‌ها به‌روز و معتبر");
  expect(source).toContain("چیدمان:");
  expect(source).toContain("هدف در برابر مقدار برنامه");
  expect(source).toContain("Object.values(currentPlan.nutrients)");
  expect(source).toContain("تاریخچه نسخه‌ها");
  expect(source).toContain("دانلود نسخه PDF برنامه غذایی");
  expect(source.indexOf("<BundleChoice")).toBeLessThan(source.indexOf("<NutritionPlanCard"));
  expect(source.indexOf("<NutritionPlanCard")).toBeLessThan(source.indexOf('label={generate.isPending ? "در حال ساخت برنامه"'));
  expect(source).not.toContain("<PlanStat");
  expect(source).not.toContain("<PlanContextItem");
  expect(source).not.toContain('برنامه غذایی هفتگی</Text>');
  expect(source).not.toContain("نسخه فعال و تاریخچه برنامه‌ها");
  expect(source).not.toContain("warning_codes.join");
  expect(source).not.toContain("reason_codes.join");
  expect(source).not.toContain("این برنامه قدیمی است؛ قبل از خرید یا تصمیم جدید، اتصال را بررسی کن.");
  expect(source).not.toContain("این نسخه هنوز برای استفاده نهایی فعال نشده است.");
  expect(shopping).not.toContain("warning_codes.join");
  expect(shopping).toContain("DisclosureCard");
  expect(shopping).toContain('title="لیست خرید دقیق"');
  expect(shopping).not.toContain('summary="مواد لازم برای این نسخه از برنامه"');
  expect(shopping).not.toContain('direction="rtl"');
  expect(shopping).toContain("defaultExpanded={false}");
  expect(shopping).toContain("تا تأیید پزشک، خرید نهایی را انجام نده.");
  expect(shopping).not.toContain("این لیست تازه‌سازی نشده است؛ قبل از خرید اتصال را بررسی کن.");
  expect(shopping).not.toContain("قیمت نهایی تا تأیید پزشک نمایش داده نمی‌شود.");
  expect(shopping).toContain("api.getShoppingList(planId)");
  expect(shopping).toContain("approvedShoppingPriceVisibility");
});
