export {
  bodyRegions,
  equipment,
  exerciseCautionTags,
  exerciseContentTypes,
  exerciseLabels,
  exerciseTypes,
  difficulties,
  mediaPresentations,
  mediaRoles,
  mediaTypes,
  movementPatterns,
  muscleFocuses,
  muscleFocusesByMuscle,
  muscleGroups,
} from "@fitician/core/exercises";
export type {
  BodyRegion,
  BodyRegionCategory,
  Difficulty,
  Equipment,
  ExerciseCategories,
  ExerciseCategory,
  ExerciseContentType,
  ExerciseCautionTag,
  ExerciseDetail,
  ExerciseFilters,
  ExerciseLabel,
  ExerciseMediaAsset,
  ExerciseSummary,
  ExerciseType,
  MediaPresentation,
  MediaRole,
  MediaType,
  MuscleFocus,
  MuscleFocusCategory,
  MuscleGroup,
  MovementPattern,
  PaginatedExercises,
  PrescriptionMode,
} from "@fitician/core/exercises";
